// Projects `.env.local` into `popup/config.js`, which the popup loads as a
// plain script. The extension has no bundler, so this is the only way an env
// var can reach runtime code; the output is gitignored for the same reason the
// source is, since `MCP_API_KEY` is a shared bearer token.
//
// Run `npm run config` after editing `.env.local`, then reload the extension.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, ".env.local");
const configTarget = resolve(root, "popup/config.js");

function readEnv(path) {
  let contents;
  try {
    contents = readFileSync(path, "utf8");
  } catch {
    return null;
  }

  const env = {};
  for (const line of contents.split("\n")) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!match) continue;
    env[match[1]] = match[2].trim().replace(/^["']|["']$/g, "");
  }
  return env;
}

function requireEnv(path) {
  const env = readEnv(path);
  if (!env) {
    throw new Error(`${path} not found — copy the URL and key into it first.`);
  }
  return env;
}

const env = requireEnv(source);
const missing = ["UPLOW_MCP_URL", "MCP_API_KEY"].filter((key) => !env[key]);
if (missing.length) {
  throw new Error(`.env.local is missing ${missing.join(" and ")}.`);
}

// The host must also appear in the manifest's `host_permissions`, or the
// popup's fetch is blocked before it leaves the browser.
const host = new URL(env.UPLOW_MCP_URL).host;
const manifest = JSON.parse(readFileSync(resolve(root, "manifest.json"), "utf8"));
const permitted = manifest.host_permissions.some((pattern) => {
  const patternHost = pattern.replace(/^https?:\/\//, "").replace(/\/.*$/, "");
  return patternHost === host || patternHost === host.replace(/:\d+$/, "");
});
if (!permitted) {
  throw new Error(
    `${host} is not in manifest.json host_permissions — add it, or the upload will be blocked by CORS.`,
  );
}

mkdirSync(dirname(configTarget), { recursive: true });
writeFileSync(
  configTarget,
  `// Generated by \`npm run config\` from .env.local. Do not edit or commit.\n` +
    `globalThis.__uplowConfig = ${JSON.stringify(
      { url: env.UPLOW_MCP_URL, key: env.MCP_API_KEY },
      null,
      2,
    )};\n`,
);

console.log(`Wrote popup/config.js pointing at ${env.UPLOW_MCP_URL}`);
